### ISSUE TITLE
Missing inertia values in xacro files

### ISSUE THREAD

**Issue by sjauhri** [pal-robotics/tiago_robot#12]
In two xacro files 'arm.urdf.xacro' and 'ftsensor.urdf.xacro', some of the inertia matrices are zero-ed out.

https://github.com/pal-robotics/tiago_robot/blob/fcaba6299d8cb34e1a93ef86bb70c62fde64bb55/tiago_description/urdf/arm/arm.urdf.xacro#L250
https://github.com/pal-robotics/tiago_robot/blob/fcaba6299d8cb34e1a93ef86bb70c62fde64bb55/tiago_description/urdf/sensors/ftsensor.urdf.xacro#L50
https://github.com/pal-robotics/tiago_robot/blob/fcaba6299d8cb34e1a93ef86bb70c62fde64bb55/tiago_description/urdf/sensors/ftsensor.urdf.xacro#L21

So, upon generating urdfs with these files, some links have zero inertia values (For instance, for a tiago_dual it affects the links: arm_left_tool_link , wrist_left_ft_link, wrist_left_ft_tool_link, arm_right_tool_link, wrist_right_ft_link, wrist_right_ft_tool_link)

Can these values be updated to the true inertia values?

Why this is an issue?:
I'm trying to load the Tiago urdf model in PyBullet and, if zero, PyBullet will load very large inertia values by default. This breaks the PyBullet physics simulation.

**Comment by saikishor** [comment]
Hello @sjauhri,

This issue has already been fixed in this commit https://github.com/pal-robotics/tiago_robot/commit/5db0da4015d0ce1699a815fd0a73e5ce51ff36b2. Thank you for reporting the issue. 

Best Regards,
PAL Robotics Team.
