### ISSUE TITLE
Tiago Robot shutting down at 20% loading with a click sound from the base

### ISSUE THREAD

**Issue by adnan-saood** [pal-robotics/tiago_robot#26]
Hello, I am facing perhaps an electrical problem, not software. I came here hoping someone faced the same thing before.

We have a Tiago robot in the uni lab, it has not been powered up lately for quite some time. I wanted to power it up after charging for almost 1 hour, but it always reaches the loading percentage of 20% on the small screen near the power button, and I hear a click sound coming from the base, then everything goes down.

**After this** I have to lock the keyhole (turn the key CCW) and then unlock it again (turn the key CW) to get the power button to work again, then it all repeats.

Did anyone face the same thing or can point me to what to do? BTW I am charging it directly from the charger as the user manual recommends for powered down robots.

I can provide a link to a video file showing the problem happen in realtime if it helps.

Thank you in advance!

Sincerely.

**Comment by saikishor** [comment]
Hello @adnan-saood,

Thank you for writing to us. All the hardware or software issues of our robots from our clients should go through the support ticket system. You can access the support page using the link : [https://support.pal-robotics.com/](https://support.pal-robotics.com/). Once the support ticket is opened, we will get back to you at as soon as possible. 

I'll be closing this issue as it doesn't belong here :)

Have a great day,

Thank you,

Best Regards,
PAL Robotics Team.
