### ISSUE TITLE
migrate from gazebo classic

### ISSUE THREAD

**Issue by david-wb** [pal-robotics/tiago_robot#29]
Hello, I was wondering if there was any plan to migrate this repo to support the new version of gazebo now that [gazebo-classic is nearly EOL and no longer supported in ROS2 Jazzy / Ubuntu 24.04](https://community.gazebosim.org/t/gazebo-classic-end-of-life/2563)? I think mainly the gazebo plugins would need to be updated but perhaps there is more to it than that.

**Comment by saikishor** [comment]
Hello!

We are sorry for the delayed response. There are some ongoing community contributions on this. You can find more info here: https://github.com/pal-robotics/tiago_simulation/issues/27

Thank you,

Best Regards,
PAL Robotics Team
